### PR TITLE
Added some much needed description

### PR DESCRIPTION
**Pull request by christopherccrichards**

### CODE REVIEW

**Comment by christopherccrichards** [comment]
Can you take care of the pull request buddy

**Comment by christopherccrichards** [comment]
Thanks @AnthonyCRichards for taking care of this

**Comment by AnthonyCRichards** [comment]
this is really stupid 
why would i add something like this to my branch
no way!

**Comment by christopherccrichards** [comment]
Thanks man - @AnthonyCRichards just check it in

**Pull request merged**
